### ISSUE TITLE
테이블에 해당하는 엔티티 생성

### ISSUE THREAD

**Issue by ki-met-hoon** [ki-met-hoon/Houp#2]
## Description

요양시설, 진료시간, 진료분야, 시설상세내용, 사용자 정보, 영양제 테이블에 관한 엔티티 생성

## Tasks
- [x] NursingFacilities Entity 생성
- [x] ClinicHours Entity 생성
- [x] ClinicDepartment Entity 생성
- [x] FacilityDeatils Entity 생성
- [x] UserInfo Entity 생성
- [x] Supplement Entity 생성
- [x] yml 파일 설정
