### ISSUE TITLE
병원 데이터 최종.xlsx  내 각 행의 데이터를 Houp DB에 삽입

### ISSUE THREAD

**Issue by ki-met-hoon** [ki-met-hoon/Houp#4]
## Description

병원 데이터 최종 엑셀 파일 내 각 행에 해당하는 데이터를 Houp DB 내 해당하는 테이블에 삽입

## Tasks
- [x] 병원 데이터 최종.xlsx 데이터 가져오기
- [x] 각 행을 분리하고 각 열을 파싱하기
- [x] 열에 해당하는 테이블 컬럼에 삽입
