### ISSUE TITLE
AI를 통한 추정 질병 응답 API 구현

### ISSUE THREAD

**Issue by ki-met-hoon** [ki-met-hoon/Houp#8]
## Description

* 클라이언트에게 받은 사용자 정보를 AI에게 전달 후 해당 증상에 관한 추정 질병을 응답 받는 API 구현

## Tasks
- [x] Feign Client 환경 설정
- [x] Feign Client interface 구현 
- [x] 사용자 정보 전달 DTO 구현
- [x] 추정 질병 응답 DTO 구현
- [x] diseasePredictionService 구현
